"""
song_template.py — Template for a song data file.
"""

SONG = {
    "title": "My Alice by Billy Strings",
    "sources": [
        ("UltimateGuitar", "https://tabs.ultimate-guitar.com/tab/billy-strings/my-alice-chords-4425650e"),
    ],
    "sections": [
         {
            "type": "intro",
            "label": "Intro",
            "lines": [
                ("|1m   |b7 5m |b7    |1m    |", None),
            ],
        },
        {
            "type": "verse",
            "label": "Verse 1",
            "lines": [
                ("1m                 b7               5m",
                 "Early in the fall, back deep in the woods"),
                ("b7                              1m ",
                 "The first hint of frost is upon you"),
                ("         b7                         1m ",
                 "About a mile beyond a field's stone wall"),
                ("b7                              1m ",
                 "It's not hard to get lost if you want to"),
                ("|b7    |1m    |", None),
                ("    1m                    b7           5m",
                 "Too far from the city to see the white lights"),
                ("  b7                        1m ",
                 "I move in the shadows under cover of night"),
                ("                            b7          1m ",
                 "Too far from the highway to blow a flat tire"),
                ("     b7                     1m ",
                 "So I stare at the ashes and fire"),
            ],
        },
        {
            "type": "solo",
            "label": "Instrumental",
            "lines": [
                ("|1m   |b7 5m |b7    |1m    |", None),
            ],
        },
        {
            "type": "verse",
            "label": "Verse 3",
            "lines": [
                ("1m                      b7         5m",
                 "Well John St. Paul is a well-known man"),
                ("   b7                       1m ",
                 "Of wealth in his skyscraper palace"),
                ("                          b7               1m ",
                 "He likes his old Cadillac prepped for long drives"),
                ("        b7                      1m ",
                 "I don't like how he looks at my Alice"),
                ("|b7    |1m    |", None),
                ("1m                     b7           5m",
                 "I work his garage with wrench in my glove"),
                ("b7                               1m ",
                 "Bring the stench of his gasoline home to my love"),
                ("                              b7       1m ",
                 "She swears once again she has all she desires"),
                ("     b7                     1m ",
                 "As I stare at the ashes and fire"),
            ],
        },
        {
            "type": "solo",
            "label": "Instrumental",
            "lines": [
                ("|1m   |b7 5m |b7    |1m    |", None),
            ],
        },
        {
            "type": "verse",
            "label": "Verse 3",
            "lines": [
                ("1m                          b7        5m",
                 "One day late last week when I got the word"),
                ("    b7                       1m ",
                 "The boss needs his Caddy all steady"),
                ("                          b7      1m ",
                 "I remembered his eyes all over my wife"),
                ("     b7                     1m ",
                 "As I carefully got my tools ready"),
                ("|b7    |1m    |", None),
                ("1m                              b7          5m",
                 "What a terrible shame should he ever break down"),
                ("     b7                               1m ",
                 "With me on his trail and so far from town"),
                ("                                   b7        1m ",
                 "If his brakes were to fail, if he blew out a tire"),
                ("   b7                         1m ",
                 "As I stared at the ashes and fire"),
            ],
        },
        {
            "type": "solo",
            "label": "Instrumental",
            "lines": [
                ("|1m   |b7 5m |b7    |1m    |", None),
            ],
        },
        {
            "type": "verse",
            "label": "Verse 3",
            "lines": [
                ("1m                      b7         5m",
                 "Well John St. Paul is a well-known man"),
                ("   b7                       1m ",
                 "Of wealth in his skyscraper palace"),
                ("                          b7               1m ",
                 "He likes his old Cadillac prepped for long drives"),
                ("        b7                      1m ",
                 "I don't like how he looks at my Alice"),
                ("        b7                      1m ",
                 "I don't like how he looks at my Alice"),
            ],
        },
    ],
}
